name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pycodestyle PyYAML
        # Добавьте шаги для установки компилятора ассемблера, если это необходимо
    - name: Run pytest with coverage
      run: |
        coverage run -m pytest --verbose
    - name: Generate coverage report
      run: |
        coverage report
    - name: Check PEP8 compliance
      run: |
        find . -type f -name "*.py" | xargs -t pycodestyle --ignore=E501,E126
        find . -type f -name "*.py" | xargs -t pycodestyle --ignore=E501,E126,E741
