name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.8 # Используйте официальный образ Python

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pep8
    - name: Run pytest with coverage
      run: |
        coverage run -m pytest --verbose
    - name: Generate coverage report
      run: |
        find . -type f -name "*.py" | xargs -t coverage report
    - name: Check PEP8 compliance
      run: |
        find . -type f -name "*.py" | xargs -t pep8 --ignore=E501,E126