name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python-tools
      options: --entrypoint ""

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: python -m pip install --upgrade pip pytest coverage pep8

    - name: Run tests with coverage
      run: python3-coverage run -m pytest --verbose

    - name: Generate coverage report
      run: |
        find . -type f -name "*.py" | xargs python3-coverage report

    - name: Check code style with PEP8
      run: |
        find . -type f -name "*.py" | xargs pep8 --ignore=E501,E126
